Habbitz Web/Models/PaymentMethod.cs
using System.ComponentModel.DataAnnotations;

namespace Habbitz_Web.Models
{
    public class PaymentMethod
    {
        [Key]
        public int Id { get; set; }
              [Required]
        public string Name { get; set; }
        
    }
}

Habbitz Web/Controllers/PaymentMethodController.cs
using Microsoft.AspNetCore.Mvc;
using Habbitz_Web.Models;
using Habbitz_Web.Data;

namespace Habbitz_Web.Controllers
{
    public class PaymentMethodController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public PaymentMethodController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            IEnumerable<PaymentMethod> paymentMethods = _dbContext.PaymentMethods;
            return View(paymentMethods);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PaymentMethod paymentMethod)
        {
            if (ModelState.IsValid)
            {
                _dbContext.PaymentMethods.Add(paymentMethod);
                _dbContext.SaveChanges();
                TempData["success"] = "PaymentMethod created successfully";
                return RedirectToAction("Index");
            }
            return View(paymentMethod);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var paymentMethodFromDb = _dbContext.PaymentMethods.Find(id);
            if (paymentMethodFromDb == null)
            {
                return NotFound();
            }
            return View(paymentMethodFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PaymentMethod paymentMethod)
        {
            if (ModelState.IsValid)
            {
                _dbContext.PaymentMethods.Update(paymentMethod);
                _dbContext.SaveChanges();
                TempData["success"] = "PaymentMethod updated successfully";
                return RedirectToAction("Index");
            }
            return View(paymentMethod);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var paymentMethodFromDb = _dbContext.PaymentMethods.Find(id);

            if (paymentMethodFromDb == null)
            {
                return NotFound();
            }
            return View(paymentMethodFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePaymentMethod(int? id)
        {
            var paymentMethodFromDb = _dbContext.PaymentMethods.Find(id);
            if (paymentMethodFromDb == null)
            {
                return NotFound();
            }
            _dbContext.PaymentMethods.Remove(paymentMethodFromDb);
            _dbContext.SaveChanges();
            TempData["success"] = "PaymentMethod deleted successfully";
            return RedirectToAction("Index");
        }

    }
}

Habbitz Web/Views/PaymentMethod/Create.cshtml
@model PaymentMethod
@{
    ViewData["Title"] = "Create";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Create Payment Method</h2>
            <hr />
        </div>
         <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" required />
        </div>
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="PaymentMethod" asp-action="Index" class="btn btn-secondary" style="150px">Back to List</a>
    </div>
</form>

Habbitz Web/Views/PaymentMethod/Delete.cshtml
@model PaymentMethod

<form method="post" asp-action="DeletePaymentMethod">
    <div class="border p-3 mt-4">
        <input asp-for="Id" hidden />
        <div class="row pb-2">
            <h2>Delete Payment Method</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" disabled />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="PaymentMethod" asp-action="Index" class="btn btn-secondary" style="150px">Back to List</a>
    </div>
</form>

Habbitz Web/Views/PaymentMethod/Edit.cshtml
@model PaymentMethod

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Edit Payment Method</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" required />
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Submit</button>
        <a asp-controller="PaymentMethod" asp-action="Index" class="btn btn-secondary" style="150px">Back to List</a>
    </div>
</form>

Habbitz Web/Views/PaymentMethod/Index.cshtml
@model IEnumerable<PaymentMethod>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Payment Methods List</h2>
        </div>
        <div class="col-6 text-end">
            <button class="btn btn-outline-success mb-2" style="color:#cc1212">  <i class="fa fa-plus fa-2x" aria-hidden="true"></i> @Html.ActionLink("Add PaymentMethod", "Create")</button>
        </div>
    </div>
    <br />
    <table class="table table-bordered table-stripped" style="width:100p%">
        <thead>
            <tr>
                <th>
                    PaymentMethod Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var payamentMethod in Model)
            {
                <tr>
                    <td>
                        @payamentMethod.Id
                    </td>
                    <td>
                        @payamentMethod.Name
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="PaymentMethod" asp-action="Edit" asp-route-id="@payamentMethod.Id"
                           class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                            <a asp-controller="PaymentMethod" asp-action="Delete" asp-route-id="@payamentMethod.Id"
                           class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>