Habbitz Web/Models/Sale.cs
using System.ComponentModel.DataAnnotations;

namespace Habbitz_Web.Models
{
    public class Sale
    {
        [Key]
        public int Id { get; set; }
              [Required]
        public string ItemPurchased { get; set; }
              [Required]
        public int Quantity { get; set; }
              [Required]
        public float Price { get; set; }
              [Required]
        public string PaymentMethod { get; set; }
        public DateTime DateOfPurchase { get; set; } = DateTime.Now;
    }
}

Habbitz Web/Controllers/SaleController.cs
using Habbitz_Web.Data;
using Habbitz_Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Habbitz_Web.Controllers
{
    public class SaleController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public SaleController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            IEnumerable<Sale> sales = _dbContext.Sales;
            return View(sales);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Sale sale)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Sales.Add(sale);
                _dbContext.SaveChanges();
                TempData["success"] = "Sale created successfully";
                return RedirectToAction("Index");
            }
            return View(sale);
        }


        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var saleFromDb = _dbContext.Sales.Find(id);
            if (saleFromDb == null)
            {
                return NotFound();
            }
            return View(saleFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Sale sale)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Sales.Update(sale);
                _dbContext.SaveChanges();
                TempData["success"] = "Sale updated successfully";
                return RedirectToAction("Index");
            }
            return View(sale);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var saleFromDb = _dbContext.Sales.Find(id);

            if (saleFromDb == null)
            {
                return NotFound();
            }
            return View(saleFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteSale(int? id)
        {
            var saleFromDb = _dbContext.Sales.Find(id);
            if (saleFromDb == null)
            {
                return NotFound();
            }
            _dbContext.Sales.Remove(saleFromDb);
            _dbContext.SaveChanges();
            TempData["success"] = "Sale deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

Habbitz Web/Views/Sale/Create.cshtml
@model Sale
@{
    ViewData["Title"] = "Create";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Create Sale</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="ItemPurchased">Item Purchased</label>
            <input asp-for="ItemPurchased" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Quantity">Quantity</label>
            <input asp-for="Quantity" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Price">Price</label>
            <input asp-for="Price" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="PaymentMethod">Payment Method</label>
            <input asp-for="PaymentMethod" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Sale" asp-action="Index" class="btn btn-secondary" style="150px">Back to List</a>
    </div>
</form>

Habbitz Web/Views/Sale/Delete.cshtml
@model Sale

<form method="post" asp-action="DeleteSale">
    <div class="border p-3 mt-4">
        <input asp-for="Id" hidden />
        <div class="row pb-2">
            <h2>Delete Sale</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="ItemPurchased">Item Purchased</label>
            <input asp-for="ItemPurchased" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Quantity">Quantity</label>
            <input asp-for="Quantity" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Price">Price</label>
            <input asp-for="Price" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="PaymentMethod">Payment Method</label>
            <input asp-for="PaymentMethod" disabled class="form-control" />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Sale" asp-action="Index" class="btn btn-secondary" style="150px">Back to List</a>
    </div>
</form>

Habbitz Web/Views/Sale/Edit.cshtml
@model Sale

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Edit Sale</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="ItemPurchased">Item Purchased</label>
            <input asp-for="ItemPurchased" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Quantity">Quantity</label>
            <input asp-for="Quantity" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Price">Price</label>
            <input asp-for="Price" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="PaymentMethod">Payment Method</label>
            <input asp-for="PaymentMethod" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Submit</button>
        <a asp-controller="Sale" asp-action="Index" class="btn btn-secondary" style="150px">Back to List</a>
    </div>
</form>

Habbitz Web/Views/Sale/Index.cshtml
@model IEnumerable<Sale>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Sales List</h2>
        </div>
        <div class="col-6 text-end">
            <button class="btn btn-outline-success mb-2" style="color:#cc1212">  <i class="fa fa-plus fa-2x" aria-hidden="true"></i> @Html.ActionLink("Add Sale", "Create")</button>
        </div>
    </div>
    <br />
    <table class="table table-bordered table-stripped" style="width:100p%">
        <thead>
            <tr>
                <th>
                    Sale ID
                </th>
                <th>
                    Item Purchased
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Price
                </th>
                <th>
                    Payment Method
                </th>
                <th>
                    Date of Sale
                </th>
                <th>Actions </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var sale in Model)
            {
                <tr>
                    <td>
                        @sale.Id
                    </td>
                    <td>
                        @sale.ItemPurchased
                    </td>
                    <td>
                        @sale.Quantity
                    </td>
                    <td>
                        @sale.Price
                    </td>
                    <td>
                        @sale.PaymentMethod
                    </td>
                    <td>
                        @sale.DateOfPurchase
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Sale" asp-action="Edit" asp-route-id="@sale.Id"
                           class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                            <a asp-controller="Sale" asp-action="Delete" asp-route-id="@sale.Id"
                           class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>