Habbitz Web/Models/Vaccine.cs
using System.ComponentModel.DataAnnotations;

namespace Habbitz_Web.Models
{
    public class Vaccine
    {
        [Key]
        public int Id { get; set; }
              [Required]
        public string Name { get; set; }
              [Required]
        public string Description { get; set; }
              [Required]
        public string Purpose { get; set; }
              [Required]
        public string Alternative { get; set; }
              [Required]
        public DateTime ExpiryDate { get; set; }
        public DateTime PurchaseDate { get; set; } = DateTime.Now;
               [Required]
        public int Quantity { get; set; }
              [Required]
        public string Amount { get; set; }
              [Required]
        public string Currency { get; set; }
    }
}

Habbitz Web/Controllers/VaccineController.cs
using Habbitz_Web.Data;
using Habbitz_Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Habbitz_Web.Controllers
{
    public class VaccineController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public VaccineController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            IEnumerable<Vaccine> vaccines = _dbContext.Vaccines;
            return View(vaccines);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Vaccine vaccine)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Vaccines.Add(vaccine);
                _dbContext.SaveChanges();
                TempData["success"] = "Vaccine created successfully";
                return RedirectToAction("Index");
            }
            return View(vaccine);
        }


        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var vaccineFromDb = _dbContext.Vaccines.Find(id);
            if (vaccineFromDb == null)
            {
                return NotFound();
            }
            return View(vaccineFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Vaccine vaccine)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Vaccines.Update(vaccine);
                _dbContext.SaveChanges();
                TempData["success"] = "Vaccine updated successfully";
                return RedirectToAction("Index");
            }
            return View(vaccine);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var vaccineFromDb = _dbContext.Vaccines.Find(id);

            if (vaccineFromDb == null)
            {
                return NotFound();
            }
            return View(vaccineFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteVaccine(int? id)
        {
            var vaccineFromDb = _dbContext.Vaccines.Find(id);
            if (vaccineFromDb == null)
            {
                return NotFound();
            }
            _dbContext.Vaccines.Remove(vaccineFromDb);
            _dbContext.SaveChanges();
            TempData["success"] = "Vaccine deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

Habbitz Web/Views/Vaccine/Create.cshtml
@model Vaccine

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Create Vaccine</h2>
            <hr />
        </div>
        
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" required />
        </div>
        <div class="mb-3">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" class="form-control" required/>
        </div>
        <div class="mb-3">
            <label asp-for="Purpose">Purpose</label>
            <input asp-for="Purpose" class="form-control" required />
        </div>
        <div class="mb-3">
            <label asp-for="Alternative">Alternative</label>
            <input asp-for="Alternative" class="form-control" required />
        </div>
        <div class="mb-3">
            <label asp-for="ExpiryDate">Expiry Date</label>
            <input asp-for="ExpiryDate" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Quantity">Quantity</label>
            <input asp-for="Quantity" class="form-control" required />
        </div>
        <div class="mb-3">
            <label asp-for="Amount">Amount</label>
            <input asp-for="Amount" class="form-control" required />
        </div>
        <div class="mb-3">
            <label asp-for="Currency">Currency</label>
            <input asp-for="Currency" class="form-control" required />
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Vaccine" asp-action="Index" class="btn btn-secondary" style="150px">Back to List</a>
    </div>
</form>

Habbitz Web/Views/Vaccine/Delete.cshtml
@model Vaccine

<form method="post" asp-action="DeleteVaccine">
    <div class="border p-3 mt-4">
        <input asp-for="Id" hidden />
        <div class="row pb-2">
            <h2>Delete Vaccine</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Purpose">Purpose</label>
            <input asp-for="Purpose" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Alternative">Alternative</label>
            <input asp-for="Alternative" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="ExpiryDate">Expiry Date</label>
            <input asp-for="ExpiryDate" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Quantity">Quantity</label>
            <input asp-for="Quantity" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Amount">Amount</label>
            <input asp-for="Amount" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Currency">Currency</label>
            <input asp-for="Currency" disabled class="form-control" />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Vaccine" asp-action="Index" class="btn btn-secondary" style="150px">Back to List</a>
    </div>
</form>

Habbitz Web/Views/Vaccine/Edit.cshtml
@model Vaccine

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Edit Vaccine</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Purpose">Purpose</label>
            <input asp-for="Purpose" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Alternative">Alternative</label>
            <input asp-for="Alternative" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="ExpiryDate">Expiry Date</label>
            <input asp-for="ExpiryDate" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Quantity">Quantity</label>
            <input asp-for="Quantity" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Amount">Amount</label>
            <input asp-for="Amount" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Currency">Currency</label>
            <input asp-for="Currency" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Submit</button>
        <a asp-controller="Vaccine" asp-action="Index" class="btn btn-secondary" style="150px">Back to List</a>
    </div>
</form>

Habbitz Web/Views/Vaccine/Index.cshtml
@model IEnumerable<Vaccine>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Vaccines List</h2>
        </div>
        <div class="col-6 text-end">
            <button class="btn btn-outline-success mb-2" style="color:#cc1212">  <i class="fa fa-plus fa-2x" aria-hidden="true"></i> @Html.ActionLink("Add Vaccine", "Create")</button>
        </div>
    </div>
    <br />
    <table class="table table-bordered table-stripped" style="width:100p%">
        <thead>
            <tr>
                <th>
                    Vaccine Id
                </th>
                <th>
                    Vaccine Name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Purpose
                </th>
                <th>
                    Alternative
                </th>
                <th>
                    Expiry Date
                </th>
                <th>
                    Purchase Date
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Currency
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var vaccine in Model)
            {
                <tr>
                    <td>
                        @vaccine.Id
                    </td>
                    <td>
                        @vaccine.Name
                    </td>
                    <td>
                        @vaccine.Description
                    </td>
                    <td>
                        @vaccine.Purpose
                    </td>
                    <td>
                        @vaccine.Alternative
                    </td>
                    <td>
                        @vaccine.ExpiryDate
                    </td>
                    <td>
                        @vaccine.PurchaseDate
                    </td>
                    <td>
                        @vaccine.Quantity
                    </td>
                    <td>
                        @vaccine.Amount
                    </td>
                    <td>
                        @vaccine.Currency
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Vaccine" asp-action="Edit" asp-route-id="@vaccine.Id"
                           class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                            <a asp-controller="Vaccine" asp-action="Delete" asp-route-id="@vaccine.Id"
                           class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>